print("Today is a good day!")
print(1+1)
print("---------")
print(24*56)
print("J'aime les pommes, il aime les poires.")
print("---------")
print("J'aime les pommes,")
print("il aime les poires.")
print("---------")
# saut de ligne \n
print("J'aime les pommes,\nil aime les poires.")